apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}
type: Opaque
data:
  MY_SUPER_SECRET_1: {{ .Values.env.secrets.MY_SUPER_SECRET_1 | b64enc | quote }}
  MY_SUPER_SECRET_2: {{ .Values.env.secrets.MY_SUPER_SECRET_2 | b64enc | quote }}
